### PR TITLE
Make Unregister a no-op Fixes #77

### LINKED ISSUE #77: Unregister does not reset IsRegistered to false
If I call `RegisterInstance(...)` and then `Unregister()`, `IsRegistered` continues to return true.

Any code using this to perform conditional registration checks will subsequently not register, and then crash when attempting to resolve an MSBuild assembly.

### PR DESCRIPTION
**Pull request by Forgind**
Unregister currently looks to see if we had previously registered MSBuild, and if so, it undoes our resolver but leaves IsRegistered set to true. This basically means we can't unregister then re-register it, at least not via MSBuildLocator. One fix could be ensuring that IsRegistered is set to false at the end of Unregister, but since we no longer register specific assemblies anyway, making it a no-op seems more reasonable. There's no need to unregister anyway.

### CODE REVIEW

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 1]
```diff
@@ -290,19 +290,6 @@ Assembly TryLoadAssembly(AssemblyName assemblyName)
         /// </remarks>
```
Comment (rainersigwald) [inline src/MSBuildLocator/MSBuildLocator.cs:290]: Change the doc comment too to say "don't call this" please.

**Review by rainersigwald — APPROVED** [review]

**Comment by yaakov-h** [comment]
Can it be given ObsoleteAttribute as well, and/or hidden with EditorBrowsable?

**Comment by Forgind** [comment]
> Can it be given ObsoleteAttribute as well, and/or hidden with EditorBrowsable?

Obsolete would throw a warning, so I don't think I can do that, but I think EditorBrowsable is fine! Thanks for the suggestion!

**Comment by rainersigwald** [comment]
Agreed (though we can think about having a less aggressive breaking change policy in this repo than in MSBuild proper).

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 2]
```diff
@@ -8,6 +8,7 @@
 using System.Linq;
 using System.Reflection;
 using System.Text;
+using System.ComponentModel;
```
Comment (yaakov-h) [inline src/MSBuildLocator/MSBuildLocator.cs:11]: Looking at the existing list, are these normally sorted alphabetically?

Comment (Forgind) [reply src/MSBuildLocator/MSBuildLocator.cs]: Fixed, thanks

**Review by yaakov-h — APPROVED** [review]
