### PR TITLE
Load all assemblies from the MSBuild folder if not already loaded

### LINKED ISSUE #38: Should System.Collections.Immutable and System.Threading.Tasks.Dataflow be supported?
The Microsoft.Build assembly references the System.Collections.Immutable and System.Threading.Tasks.Dataflow assemblies, both living in the MSBuild build folder. I saw failures building WPF projects in our build application and I got around it by adding assembly resolving support for System.Collections.Immutable.

### LINKED ISSUE #103: .net 5 works poorly with latest preview prerelase.
When using a XUnit test project, `System.Numerics.Vectors` and `System.Runtime.CompilerServices.Unsafe` are already loaded in the process when the a module initializer is run. That is as early as can be.

```cs
	public static class ModInit
	{
		[ModuleInitializer]
		public static void Init()
		{
			try
			{				
				if (!MSBuildLocator.IsRegistered)
				{
					MSBuildLocator.RegisterDefaults();
				}
			}
			catch (InvalidOperationException ex)
			{
				System.Diagnostics.Trace.WriteLine(ex);
			}
		}
	}
```

```text
Microsoft.Build.Locator.MSBuildLocator.RegisterInstance was called, but MSBuild assemblies were already loaded.
Ensure that RegisterInstance is called before any method that directly references types in the Microsoft.Build namespace has been called.
This dependency arises from when a method is just-in-time compiled, so if it breaks even if the reference to a Microsoft.Build type has not been executed.
For more details, see aka.ms/RegisterMSBuildLocator
Loaded MSBuild assemblies: System.Numerics.Vectors, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

So having these assemblies in the vector

```cs
        private static readonly string[] s_msBuildAssemblies =
        {
            "Microsoft.Build",
            "Microsoft.Build.Engine",
            "Microsoft.Build.Framework",
            "Microsoft.Build.Tasks.Core",
            "Microsoft.Build.Utilities.Core",
            "System.Runtime.CompilerServices.Unsafe",
            "System.Numerics.Vectors"
        };
```
seems like a bad idea.

If they are needed as a dependency, that should be separated from if there are msbuild assemblies loaded in the process.

### PR DESCRIPTION
**Pull request by Forgind**
Changes the check for previously loaded assemblies to only fail if we already registered them via MSBuildLocator. Then adds previously loaded assemblies to the list of loaded assemblies so they aren't loaded again.

This may cause version mismatch issues, but if you had previously loaded some but not all of our assemblies, I'd say that's something for you to figure out. 😄 

Fixes #103.

Also Fixes #38.

### CODE REVIEW

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 1]
```diff
@@ -200,27 +198,32 @@ Assembly TryLoadAssembly(AssemblyName assemblyName)
...
-                                Unregister();
-                            }
-
-                            assembly = Assembly.LoadFrom(targetAssembly);
-                            loadedAssemblies.Add(assemblyName.FullName, assembly);
-                            return assembly;
+                            loadedAssemblies.Add(assemblyName.FullName, loadedAssembly);
+                            return loadedAssembly;
                         }
+
```
Comment (Forgind) [inline src/MSBuildLocator/MSBuildLocator.cs:217]: delete

File: samples/BuilderApp/BuilderApp.csproj [hunk 2]
```diff
@@ -2,7 +2,7 @@
 
   <PropertyGroup>
     <OutputType>Exe</OutputType>
-    <TargetFrameworks>net471;netcoreapp2.1</TargetFrameworks>
+    <TargetFrameworks>net471;netcoreapp3.1</TargetFrameworks>
```
Comment (rainersigwald) [inline samples/BuilderApp/BuilderApp.csproj:5]: Is this needed?

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 3]
```diff
@@ -37,7 +35,7 @@ public static class MSBuildLocator
 #endif
 
         // Used to determine when it's time to unregister the registeredHandler.
```
Comment (rainersigwald) [inline src/MSBuildLocator/MSBuildLocator.cs:37]: Stale comment

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 4]
```diff
@@ -200,27 +199,17 @@ Assembly TryLoadAssembly(AssemblyName assemblyName)
...
                 lock (loadedAssemblies)
                 {
-                    Assembly assembly;
-                    if (loadedAssemblies.TryGetValue(assemblyName.FullName, out assembly))
+                    if (loadedAssemblies.TryGetValue(assemblyName.FullName, out Assembly assembly))
                     {
                         return assembly;
                     }
 
-                    if (IsMSBuildAssembly(assemblyName))
```
Comment (rainersigwald) [inline src/MSBuildLocator/MSBuildLocator.cs:209]: Delete no-longer-needed `IsMSBuildAssembly` method. It's used in `LoadedMsBuildAssemblies` but I think that should now just return what's currently the local value `loadedAssemblies` (I guess it needs to become instance).

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 5]
```diff
@@ -200,27 +199,17 @@ Assembly TryLoadAssembly(AssemblyName assemblyName)
...
+                    string targetAssembly = Path.Combine(msbuildPath, assemblyName.Name + ".dll");
```
Comment (rainersigwald) [inline src/MSBuildLocator/MSBuildLocator.cs:207]:
```suggestion
                    // Look in the MSBuild folder for any unresolved reference--it may be a dependency
                    // of MSBuild or a task.
                    string targetAssembly = Path.Combine(msbuildPath, assemblyName.Name + ".dll");
```

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 6]
```diff
@@ -239,7 +228,7 @@ public static void Unregister()
             if (!IsRegistered)
             {
                 var error = $"{typeof(MSBuildLocator)}.{nameof(Unregister)} was called, but no MSBuild instance is registered." + Environment.NewLine;
-                if (numResolvedAssemblies == 0)
+                if (!registerCalled)
                 {
                     error += $"Ensure that {nameof(RegisterInstance)}, {nameof(RegisterMSBuildPath)}, or {nameof(RegisterDefaults)} is called before calling this method.";
```
Comment (rainersigwald) [inline src/MSBuildLocator/MSBuildLocator.cs:233]: I think this whole error system might be kinda useless now--we no longer really have the concept of `Unregister` since the assemblies we might resolve is now unbounded. This change is OK but I think it's worth thinking of just rewriting this whole thing to do nothing.

**Review by rainersigwald — CHANGES_REQUESTED** [review]

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 7]
```diff
@@ -50,9 +48,7 @@ public static class MSBuildLocator
         /// <remarks>
         ///     If any Microsoft.Build assemblies are already loaded into the current AppDomain, the value will be false.
         /// </remarks>
-        public static bool CanRegister => !IsRegistered && !LoadedMsBuildAssemblies.Any();
-
-        private static IEnumerable<Assembly> LoadedMsBuildAssemblies => AppDomain.CurrentDomain.GetAssemblies().Where(IsMSBuildAssembly);
+        public static bool CanRegister => !IsRegistered && !loadedAssemblies.Any();
```
Comment (rainersigwald) [inline src/MSBuildLocator/MSBuildLocator.cs:51]: Naturally looking at the diff that's the result of the change I asked you to make revealed to me that I was wrong and this isn't what we want. I'll push a fix.

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 8]
```diff
@@ -239,7 +230,7 @@ public static void Unregister()
             if (!IsRegistered)
             {
                 var error = $"{typeof(MSBuildLocator)}.{nameof(Unregister)} was called, but no MSBuild instance is registered." + Environment.NewLine;
-                if (numResolvedAssemblies == 0)
+                if (!registerCalled)
```
Comment (Forgind) [inline src/MSBuildLocator/MSBuildLocator.cs:233]: This error message is now wrong. Unregister isn't called automatically, so the only way IsRegistered would be false but registerCalled would be true is if they manually Unregistered twice, which probably isn't a big thing. I'd prefer to unset registerCalled here and keep just the one message.

File: src/MSBuildLocator/MSBuildLocator.cs [hunk 9]
```diff
@@ -37,7 +35,7 @@ public static class MSBuildLocator
 #endif
 
         // Used to determine when it's time to unregister the registeredHandler.
-        private static int numResolvedAssemblies;
+        private static bool registerCalled = false;
```
Comment (Forgind) [inline src/MSBuildLocator/MSBuildLocator.cs:38]: Stale comment—we don't unregister the registeredHandler.

File: src/MSBuildLocator/MSBuildLocator.cs (hunk 8 above)
Comment (rainersigwald) [reply src/MSBuildLocator/MSBuildLocator.cs:233]: I'm not 100% sure I understand what you mean but go ahead and do that.

**Review by rainersigwald — APPROVED** [review]
